function sysAnalyticJacobians = createJacobianMatrixFunctions(system)

   system.equation.analyticMatrixA = ...
      matlabFunction(system.statespace.A, ...
      'Optimize',false, ...
      'Vars',[system.vector.systemInput{:,1},system.vector.elements{:,1},system.vector.state{:,1}]);

   system.equation.analyticMatrixB = ...
      matlabFunction(system.statespace.B, ...
      'Optimize',false, ...
      'Vars',[system.vector.systemInput{:,1},system.vector.elements{:,1},system.vector.state{:,1}]);

   system.equation.analyticMatrixC = ...
      matlabFunction(system.statespace.C, ...
      'Optimize',false, ...
      'Vars',[system.vector.systemInput{:,1},system.vector.elements{:,1},system.vector.state{:,1}]);

   system.equation.analyticMatrixD = ...
      matlabFunction(system.statespace.D, ...
      'Optimize',false, ...
      'Vars',[system.vector.systemInput{:,1},system.vector.elements{:,1},system.vector.state{:,1}]);

   sysAnalyticJacobians = system;

end